import jsPDF from "jspdf";
import axios from "axios";

function ReportButton() {

  const generateReport = async () => {

    try {

      const statusRes = await axios.get(
        "http://driver-drowsiness-backends.onrender.com/status"
      );

      const statsRes = await axios.get(
        "http://driver-drowsiness-backends.onrender.com/stats"
      );

      const analyticsRes = await axios.get(
        "http://driver-drowsiness-backends.onrender.com/analytics"
      );

      const screenshotRes = await axios.get(
        "http://driver-drowsiness-backends.onrender.com/latest-screenshot"
      );

      const status = statusRes.data;
      const stats = statsRes.data;
      const analytics = analyticsRes.data;

      const doc = new jsPDF();

      doc.setFillColor(15, 23, 42);

doc.rect(
  0,
  0,
  210,
  35,
  "F"
);

doc.setTextColor(
  255,
  255,
  255
);

doc.setFontSize(22);

doc.text(
  "AI DRIVER DROWSINESS REPORT",
  20,
  22
);

doc.setTextColor(
  0,
  0,
  0
);

      doc.setFontSize(12);

      doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        20,
        50
      );

      doc.line(20, 40, 190, 40);

      doc.text(
        `Driver State: ${status.state}`,
        20,
        70
      );

      doc.text(
        `EAR: ${status.ear}`,
        20,
        80
      );

      doc.text(
        `MAR: ${status.mar}`,
        20,
        90
      );

      doc.text(
        `Monitoring Time: ${stats.uptime}`,
        20,
        100
      );

      doc.text(
        `Total Alerts: ${stats.alerts}`,
        20,
        110
      );

      doc.line(20, 120, 190, 120);

      doc.roundedRect(
  15,
  125,
  180,
  65,
  3,
  3
);

      doc.setFontSize(16);

      doc.text(
        "Analytics Summary",
        20,
        135
      );

      doc.setFontSize(12);

      doc.text(
        `Average EAR: ${analytics.avgEAR}`,
        20,
        150
      );

      doc.text(
        `Average MAR: ${analytics.avgMAR}`,
        20,
        160
      );

      doc.text(
        `Drowsy Percentage: ${analytics.drowsyPercent}%`,
        20,
        170
      );

      doc.text(
        `Detection Accuracy: 94.6%`,
        20,
        180
      );

      doc.setFontSize(16);

doc.text(
  "Safety Recommendations",
  20,
  205
);

doc.setFontSize(12);

doc.text(
  "- Take breaks every 2 hours",
  25,
  218
);

doc.text(
  "- Stay hydrated while driving",
  25,
  228
);

doc.text(
  "- Avoid driving when sleepy",
  25,
  238
);

doc.setFontSize(10);

doc.text(
  "Generated by AI Driver Drowsiness Detection System",
  20,
  285
);

      if (screenshotRes.data.image) {

        const imgUrl =
          `http://driver-drowsiness-backends.onrender.com/screenshot/${screenshotRes.data.image}`;

        const img = new Image();

        img.crossOrigin = "Anonymous";

        img.onload = () => {

          doc.addPage();

          doc.setFontSize(18);

          doc.text(
  "Latest Drowsiness Event Screenshot",
  20,
  20
);

          doc.addImage(
            img,
            "JPEG",
            15,
            35,
            180,
            120
          );

          doc.save(
            "AI_Drowsiness_Report.pdf"
          );
        };

        img.src = imgUrl;

        

      } else {

        doc.save(
          "AI_Drowsiness_Report.pdf"
        );
      }

    } catch (error) {

      console.log(error);

      alert(
        "Failed to generate report"
      );

    }

  };

  return (

    <button
      onClick={generateReport}
      className="bg-green-600 hover:bg-green-700 px-6 py-3 rounded-xl font-semibold"
    >
      📄 Generate Full Report
    </button>

  );
}

export default ReportButton;